documentation:
  title: 'API 说明文档'
  description: 'Wechat Server API 说明文档'
server:
  host: '0.0.0.0'
  port: 80
db:
  host: '0.0.0.0'
  port: 27017
  db_name: wechatServer
wechatServer:
  url: https://api.weixin.qq.com/
  appID: 'wx289319afa0c7b949'
  appSecret: '85da1a8baeb80dafc9611032185856ce'
  token: "wxexpress"
